Spiffs refactor
Behn4m/project_DeskHub pull request #2
Opened 2024-01-07 07:53 UTC by ehsanziyaee

Make Spiffs thread-safe

2024-01-08 16:19 UTC, Behn4m requested changes
the PR is SIFFS refactor but 445 files are updated! make sure your PR is includes updates only related to the subject

2024-01-08 20:26 UTC, Behn4m commented on components/nvsFlash/SpiffsManger.c
> +// }
remove commented lines

2024-01-08 20:32 UTC, Behn4m commented on components/nvsFlash/SpiffsManger.c
> +        ESP_LOGE(TAG, "Can not access to Spiffs");
it's good idea to mention that timeout happened

2024-01-08 20:33 UTC, Behn4m commented on components/nvsFlash/SpiffsManger.c
> +                ESP_LOGE(TAG, "Unable to remove the file.");
same here, if timeout happens let user see in the error log

2024-01-08 20:36 UTC, Behn4m commented on components/nvsFlash/SpiffsManger.c
> +                ret = 0;
Boolean values 'true' or 'false' should be assigned to the bool variable.

2024-01-08 20:40 UTC, Behn4m commented on components/nvsFlash/SpiffsManger.c
> +static bool SpiffsExistenceCheck(char *addressInSpiffs)
`SpiffscheckFileExists()` makes more sense for this function

2024-01-09 07:42 UTC, MohammadAbbasi76 commented on components/nvsFlash/SpiffsManger.c
> +static bool SpiffsExistenceCheck(char *addressInSpiffs)
my suggestion is  "/**
@brief Searches for a file in the SPIFFS file system using the provided user-supplied address.
This function takes an address from the user, performs a search in the SPIFFS file system,
and attempts to locate a file with the specified address. If the file is found, the function
returns true; otherwise, it returns false.
@param addressInSpiffs The address of the file in the SPIFFS.
@return True if the file is found, false otherwise.
*/"

2024-01-09 07:42 UTC, MohammadAbbasi76 commented on components/nvsFlash/SpiffsManger.c
> + *@brief Read the contents of a file in the SPIFFS file system and store it in a buffer.
some where param in comment have [in] , some where does'n have , please add [in] for all of them 
 * @param 
 
 * @param[in]

2024-01-09 07:42 UTC, MohammadAbbasi76 commented on components/nvsFlash/SpiffsManger.c
> +static void parseOutputJSON(const char *jsonStr)
naming is different with other function , most be ParseOutputJSON

2024-01-09 08:00 UTC, ehsanziyaee commented on components/nvsFlash/SpiffsManger.c
> +        ESP_LOGE(TAG, "Can not access to Spiffs");
there is not any time out, (actually else not run any time) cause of prevent mutual access to resources by mutex.

2024-01-09 08:02 UTC, ehsanziyaee commented on components/nvsFlash/SpiffsManger.c
> +                ret = 0;
solve it

2024-01-09 08:30 UTC, ehsanziyaee commented on components/nvsFlash/SpiffsManger.c
> +static void parseOutputJSON(const char *jsonStr)
solve it

2024-01-09 16:49 UTC, Behn4m commented on components/nvsFlash/SpiffsManger.c
> +static bool SpiffsExistenceCheck(char *addressInSpiffs)
I mean the function name

2024-01-09 16:50 UTC, Behn4m commented
the PR name is Spiff refactor, but in includes also some updates in Spotify Interface. make sure you only update relevant files in your PR

2024-01-10 18:13 UTC, Behn4m approved these changes

2024-01-11 10:04 UTC, merged